---
title: "Linear discriminant analysis/H1N1"
output: html_notebook
---


Se realizo este trabajo utilizando una base de datos de pacientes embarazadas que debieron recibir asistencia de terapia intensiva a causa de infeccion con el virus H1N1

```{r,echo=FALSE}
library(readxl)  #permite leer archivos xlxs
datos <- read_excel("C:/Users/Magali/Desktop/IAM/Tp IAM EISIK-VALENTI.xlsx") 

```

Realizamos un analisis exploratorio de los datos

```{r}
library(tidyverse)
library(dplyr)
names(datos)
#SOFA 24hs
ggplot(data = datos, aes(x = Evolucion, y = Sofa24h)) + 
  geom_jitter(aes(color = Evolucion), size = 1, alpha = 0.7) +
  geom_boxplot(aes(color = Evolucion), alpha = 0.7) + 
  xlab('Evolucion') + 
  ylab('Sofa 24h') +
  ggtitle('SOFA 24h y evolucion') + 
  theme_minimal()

#PaO2/FiO2 al ingreso a UTI (basal)
ggplot(data = datos, aes(x = `PaO2/FiO2 al ingreso a UTI (basal)`)) + 
 geom_density(fill="#69b3a2")+ 
  xlab('Pa02/FiO2') +
  ylab('Densidad') + ggtitle(' Pa02/FiO2')

#Evolucion en UTI
tabla_evolucion <- datos %>% group_by(Evolucion) %>% summarise(Total=n()) 
tabla_evolucion
ggplot(tabla_evolucion, aes(x = Evolucion, y=Total,fill=Evolucion) ) +    
  geom_bar(width = 0.9, stat="identity",              
           position = position_dodge())+  
  ylim(c(0,100))+
  labs(x="Evolucion de pacientes en UTI", y= "Frecuencia") +   
  labs(fill = "")+                                         
  geom_text(aes(label=Total), vjust=1.6, color="black",    
              position = position_dodge(0.9),  size=4.0) +                                            theme_bw(base_size = 15)+
  ggtitle("Evolucion de pacientes en UTI")
ggplot(datos) + aes(x=Sofa24h,y=`PaO2/FiO2 al ingreso a UTI (basal)`,color=Evolucion) + 
  geom_point()  + 
  scale_x_continuous(breaks=seq(0,12,2)) +
  scale_y_continuous(breaks=seq(0,8,1)) + 
  theme_bw() +
  theme(panel.grid = element_blank())+
  ggtitle("PaO2/FiO2 vs SOFA 24hs")
```